url: http://www.advantageai.com
baseurl:

# Site settings
title: Advantage AI
email: sales@advantageai.com
description: "Advantage Ai provides consulting in data science, machine learning, spark, and artificial intelligence."

# Example fields not used: 
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Remote
  - line: Globally

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-google-tag-manger

google:
  tag_manager:
    container_id: GTM-TVXN4GD6